
version: "3"
services:
  elasticsearch:
    restart: always
    image: elasticsearch:6.4.2
    environment:
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "path.repo=/usr/share/elasticsearch/backup"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    user: "1000"
    expose:
      - "9200"
    ports:
      - "9200:9200"
    volumes:
      - ./elasticsearch.yml:/usr/share/elasticsearch/config/elasticsearch.yml

  mongo:
    image: mongo
    restart: always
    expose:
      - "27017"
    ports:
      - "27017:27017"
    volumes:
      - mongodb2:/data/db2

  redis:
    image: redis
    restart: always
    expose:
      - "6379"
    ports:
      - "6379:6379"

volumes:
  mongodb2:

